# -*- coding: utf-8 -*-
"""Medical Insurance .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LHHzMkUfd4XiRyTvTCEgI0gA7m58OmkH
"""

from google.colab import drive
drive.mount('/content/drive')

file_path="/content/drive/MyDrive/Python Project/insurance.csv"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error,
    accuracy_score,
    confusion_matrix,
    classification_report,
)

df = pd.read_csv(file_path)
print("First 5 Rows")
print(df.head())

print("\nDataset Info")
print(df.info())

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows")
print(df.duplicated().sum())

df = df.drop_duplicates()

print("\nDescriptive Statistics")
print(df.describe())
print("\nAverage Insurance Charges:", df['charges'].mean())
print("Average Age:", df['age'].mean())
print("Average BMI:", df['bmi'].mean())
print("Average Children:", df['children'].mean())

plt.figure(figsize=(8,5))
sns.histplot(df["age"], kde=True)
plt.title("Age Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df["bmi"], kde=True)
plt.title("BMI Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df["charges"], kde=True)
plt.title("Charges Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df["charges"], kde=True)
plt.title("Charges Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(x="age", y="charges", data=df)
plt.title("Age vs Charges")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(x="bmi", y="charges", data=df)
plt.title("BMI vs Charges")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x="smoker", y="charges", data=df)
plt.title("Smoker vs Charges")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x="sex", y="charges", data=df)
plt.title("Gender vs Charges")
plt.show()

temp_df = df.copy()

le = LabelEncoder()

temp_df['sex'] = le.fit_transform(temp_df['sex'])
temp_df['smoker'] = le.fit_transform(temp_df['smoker'])
temp_df['region'] = le.fit_transform(temp_df['region'])

plt.figure(figsize=(10,6))
sns.heatmap(temp_df.corr(), annot=True)
plt.title("Correlation Heatmap")
plt.show()

encoder = LabelEncoder()

df['sex'] = encoder.fit_transform(df['sex'])
df['smoker'] = encoder.fit_transform(df['smoker'])
df['region'] = encoder.fit_transform(df['region'])

X = df[['age']]
y = df['charges']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

simple_model = LinearRegression()

simple_model.fit(X_train, y_train)

y_pred = simple_model.predict(X_test)

print("\n===== Simple Linear Regression =====")

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

X_multi = df[['age', 'bmi', 'children', 'smoker']]
y_multi = df['charges']

X_train, X_test, y_train, y_test = train_test_split(
    X_multi,
    y_multi,
    test_size=0.2,
    random_state=42
)

multi_model = LinearRegression()

multi_model.fit(X_train, y_train)

y_pred_multi = multi_model.predict(X_test)

print("\n===== Multiple Linear Regression =====")

print("R2 Score:", r2_score(y_test, y_pred_multi))
print("MAE:", mean_absolute_error(y_test, y_pred_multi))
print("MSE:", mean_squared_error(y_test, y_pred_multi))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_multi)))

median_charge = df['charges'].median()

df['insurance_category'] = np.where(
    df['charges'] >= median_charge,
    1,
    0
)

X_log = df[['age', 'bmi', 'children', 'smoker']]
y_log = df['insurance_category']

X_train, X_test, y_train, y_test = train_test_split(
    X_log,
    y_log,
    test_size=0.2,
    random_state=42
)

log_model = LogisticRegression()

log_model.fit(X_train, y_train)

y_pred_log = log_model.predict(X_test)

print("\n===== Logistic Regression =====")

print("Accuracy Score:", accuracy_score(y_test, y_pred_log))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_log))

print("\nClassification Report")
print(classification_report(y_test, y_pred_log))

category_count = df['insurance_category'].value_counts()

plt.figure(figsize=(6,6))
plt.pie(
    category_count,
    labels=['Low Cost', 'High Cost'],
    autopct='%1.1f%%'
)

plt.title("High Cost vs Low Cost Customers")
plt.show()

print("\n===== Insights =====")

print("1. Smokers generally have higher insurance charges.")
print("2. Age and BMI positively affect insurance costs.")
print("3. Multiple Linear Regression performs better than Simple Linear Regression.")
print("4. Logistic Regression helps classify high-risk customers.")
print("5. Insurance companies can use this system for premium estimation.")